package xiroc.lootplus;

import java.io.File;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.mojang.realmsclient.gui.ChatFormatting;

import net.minecraft.world.storage.loot.RandomValueRange;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import xiroc.lootplus.api.LootRegistry;
import xiroc.lootplus.api.loot.LootEntryCustom;
import xiroc.lootplus.api.loot.LootFile;
import xiroc.lootplus.util.EventManager;
import xiroc.lootplus.util.Reference;

@Mod(modid = Reference.MODID, name = Reference.NAME, version = Reference.VERSION, acceptedMinecraftVersions = Reference.MINECRAFT_VERSIONS)

public class LootPlus {

	public static Gson gson = new GsonBuilder().setPrettyPrinting().create();
	public static final Logger logger = LogManager.getLogger(Reference.NAME);
	public static String directory;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = ChatFormatting.GREEN + Reference.NAME;
		data.authorList.add("XIROC");
		data.url = "https://minecraft.curseforge.com/projects/lootplus";
		data.version = Reference.VERSION;
		directory = Loader.instance().getConfigDir().getAbsolutePath();
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new EventManager());
		LootFile file = new LootFile(new LootEntryCustom[] { new LootEntryCustom("minecraft:chests/spawn_bonus_chest",
				"minecraft:diamond", "lootplus:example", new RandomValueRange(1, 64), new RandomValueRange(0F), 0F) });
		File lootFile = new File(directory + "/LootPlus/lootConfig.json");
		if (!lootFile.exists())
			file.toFile(lootFile);
		LootRegistry.register(file.loot);
	}

}
